spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    port: 8080
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성 : create, update, create-drop, validate, none
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
server:
  port: 8000