spring:
  h2:
    console:
      enabled: true
      path: /h2 # (1) Context path 변경  (브라우저 URL변경)
  datasource:
    url: jdbc:h2:mem:test # (2) JDBC URL 변경
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql # (1) 테이블 생성 파일 경로